---
# tasks file for ansible-mdadm
#

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: el.yml
  when: ansible_os_family == "RedHat"

- include: wipe_disks.yml
  when: >
        mdadm_force_wipe is defined and
        mdadm_force_wipe

- include: arrays.yml
